/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gov.pnnl.rabbitmq.volttron.example;

import java.io.IOException;

import com.rabbitmq.client.Channel;
import com.rabbitmq.client.DefaultConsumer;
import com.rabbitmq.client.Envelope;
import com.rabbitmq.client.AMQP.BasicProperties;


public class RabbitSubscription extends DefaultConsumer implements Runnable {
	private Channel channel = null;
	public RabbitSubscription(Channel channel) {
		super(channel);
		this.channel = channel;
	}
	
	@Override
	public void handleDelivery(String consumerTag, Envelope envelope, BasicProperties properties, byte[] body)
			throws IOException {
		// System.out.println(envelope.getRoutingKey());
		String message = new String(body, "UTF-8");
		System.out.println("received message " +message);
	}

	@Override
	public void run() {
		String queueName = "rabbitmq-java-test";
		String routingKey = "__pubsub__."+Config.instanceName+".#";
		
		try {
			channel.queueDeclare(queueName, false, true, true, null);
			channel.queueBind(Config.queueName, Config.exchangeName, routingKey);
			channel.basicConsume(queueName, this);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

        
		
	}
}
